# URL: Tenta ler o .env, se não achar, usa o seu MySQL local (e cria o banco se não existir!)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/lista_pedidos_db?createDatabaseIfNotExist=true&serverTimezone=UTC}

# Usuário: Tenta ler o .env, se não achar, usa o 'root' do seu PC
spring.datasource.username=${DB_USERNAME:root}

# Senha: Tenta ler o .env, se não achar, usa a sua senha local 'mateus983212'
spring.datasource.password=${DB_PASSWORD:mateus983212}

# Configurações gerais do Hibernate
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

