spring.application.name=pedidosfiliais
spring.output.ansi.enabled=always
spring.profiles.active=mysql
spring.flyway.validate-migration-naming=true

# Agora sim lê do .env, se não achar usa um padrão local
api.security.token.secret=${JWT_SECRET:burrifador}
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}