spring.application.name=pedidosfiliais
spring.output.ansi.enabled=always

spring.flyway.validate-migration-naming=true

spring.profiles.active=mysql
api.security.token.secret=${JWT_SECRET}
# Se a variável APP_FRONTEND_URL não existir, o Spring usa o localhost por padrão

app.frontend.url=localhost