# Nome da sua aplicação
spring.application.name=pedidosfiliais

# Configurações de Conexão com o MySQL
# Certifique-se que o nome após a barra (/) é o mesmo que você criou no MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/lista_pedidos_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mateus983212

# Driver do MySQL para o Java 21
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate - Aqui ele cria as tabelas sozinho baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true