# Nome da sua aplicação
spring.application.name=pedidosfiliais

# Configurações de Conexão com o H2 (Banco em memória)
spring.datasource.url=jdbc:h2:mem:lista_pedidos_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o console do H2 no navegador (acesse via: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate - Criação das tabelas baseada nas classes @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

