# Nome da sua aplicação
spring.application.name=pedidosfiliais

# Configurações de Conexão com o MySQL
# Certifique-se que o nome após a barra (/) é o mesmo que você criou no MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Driver do MySQL para o Java 21
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate - Aqui ele cria as tabelas sozinho baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true