# Nome da sua aplicação (comum para todos os bancos)
spring.application.name=pedidosfiliais
spring.output.ansi.enabled=always

spring.flyway.validate-migration-naming=true
# A MÁGICA ACONTECE AQUI:
# Mude a palavra abaixo para "mysql" ou "h2" para trocar de banco!
spring.profiles.active=mysql
api.security.token.secret=${JWT_SECRET:azulejo}